- hosts: all_hosts
  become: true
  gather_facts: false
  tasks:
    - name: pip install pip
      ansible.builtin.package:
        name: python3-pip
        state: present
    - name: install pip ansible requests joblib tqdm
      ansible.builtin.pip:
        name:
          - ansible
          - requests
          - joblib
          - tqdm
        state: present
    - name: install k3s
      ansible.builtin.command: "curl -sfL https://get.k3s.io | sh -"
      register: k3s_installation
      changed_when: "'k3s is already installed' not in k3s_installation.stdout"